import { FEATURE_RULES_VERSION, FEATURE_SCHEMA_VERSION } from "./versions";

/**
 * Machine-readable feature lineage catalog — TASK-044 requirement 18. Every
 * column that appears in a `FeatureRow` (see `types.ts`) has exactly one
 * entry here; `validateCatalogAgainstRow` in `featureValidation.ts` fails
 * fatally if a row ever has a column this catalog doesn't describe, or vice
 * versa, so the catalog can never silently drift from the real schema.
 */
export type FeatureFieldType = "numeric" | "integer" | "boolean" | "categorical" | "identifier" | "label" | "version";
export type FeatureLeakageRisk = "none" | "mitigated";

export interface FeatureFieldMeta {
  readonly name: string;
  readonly type: FeatureFieldType;
  readonly description: string;
  readonly sourceFields: readonly string[];
  readonly transformation: string;
  readonly temporalAvailabilityRule: string;
  readonly missingValuePolicy: string;
  readonly leakageRisk: FeatureLeakageRisk;
  readonly featureGroup: string;
  readonly versionIntroduced: string;
}

const V = "TASK-044";

interface TeamFieldTemplate {
  readonly key: string;
  readonly type: FeatureFieldType;
  readonly description: string;
  readonly sourceFields: readonly string[];
  readonly transformation: string;
  readonly temporalAvailabilityRule: string;
  readonly missingValuePolicy: string;
  readonly featureGroup: string;
}

const PRE_GROUP_RULE = "Reflects only matches strictly before the current timestamp group (state-engine emit-before-update guarantee).";

const CUMULATIVE_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "PriorMatchCount", type: "integer", description: "Career prior completed matches for this team.", sourceFields: ["matches.teamAId/teamBId"], transformation: "Count of prior matchHistory entries.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "PriorWins", type: "integer", description: "Career prior wins.", sourceFields: ["matches.winnerId"], transformation: "Count of won prior matches.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "PriorLosses", type: "integer", description: "Career prior losses.", sourceFields: ["matches.winnerId"], transformation: "priorMatchCount - priorWins.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "CumulativeWinRate", type: "numeric", description: "Career win rate.", sourceFields: ["matches.winnerId"], transformation: "priorWins / priorMatchCount.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when priorMatchCount is 0 (documented cold-start prior, not a measured rate).", featureGroup: "team-cumulative" },
  { key: "PriorMapsPlayed", type: "integer", description: "Career prior maps actually played.", sourceFields: ["matches.maps"], transformation: "Sum of mapsWon+mapsLost across matchHistory.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "PriorMapWins", type: "integer", description: "Career prior map wins.", sourceFields: ["matches.maps"], transformation: "Sum of mapsWon across matchHistory.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "PriorMapLosses", type: "integer", description: "Career prior map losses.", sourceFields: ["matches.maps"], transformation: "priorMapsPlayed - priorMapWins.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-cumulative" },
  { key: "CumulativeMapWinRate", type: "numeric", description: "Career map win rate.", sourceFields: ["matches.maps"], transformation: "priorMapWins / priorMapsPlayed.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when priorMapsPlayed is 0.", featureGroup: "team-cumulative" },
  { key: "IsColdStart", type: "boolean", description: "True when this team has zero prior matches in the curated dataset.", sourceFields: ["matches.teamAId/teamBId"], transformation: "priorMatchCount === 0.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Not applicable — always defined.", featureGroup: "team-cumulative" },
];

const RECENT_FORM_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "Last3MatchCount", type: "integer", description: "Number of matches in the trailing 3-match window (may be < 3 early in history).", sourceFields: ["matches"], transformation: "matchHistory.slice(-3).length.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-recent-form" },
  { key: "Last3WinRate", type: "numeric", description: "Win rate over the last 3 matches.", sourceFields: ["matches"], transformation: "wins / count over last 3.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when the window is empty.", featureGroup: "team-recent-form" },
  { key: "Last5MatchCount", type: "integer", description: "Number of matches in the trailing 5-match window.", sourceFields: ["matches"], transformation: "matchHistory.slice(-5).length.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-recent-form" },
  { key: "Last5WinRate", type: "numeric", description: "Win rate over the last 5 matches.", sourceFields: ["matches"], transformation: "wins / count over last 5.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when the window is empty.", featureGroup: "team-recent-form" },
  { key: "Last10MatchCount", type: "integer", description: "Number of matches in the trailing 10-match window.", sourceFields: ["matches"], transformation: "matchHistory.slice(-10).length.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no history.", featureGroup: "team-recent-form" },
  { key: "Last10WinRate", type: "numeric", description: "Win rate over the last 10 matches.", sourceFields: ["matches"], transformation: "wins / count over last 10.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when the window is empty.", featureGroup: "team-recent-form" },
  { key: "Last30DayMatchCount", type: "integer", description: "Matches played in the trailing 30 calendar days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where timestampMs >= now - 30d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no matches in window.", featureGroup: "team-recent-form" },
  { key: "Last30DayWinRate", type: "numeric", description: "Win rate over the trailing 30 calendar days.", sourceFields: ["matches.scheduledAt", "matches.winnerId"], transformation: "wins / count over the 30-day window.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when the window is empty.", featureGroup: "team-recent-form" },
  { key: "Last60DayMatchCount", type: "integer", description: "Matches played in the trailing 60 calendar days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where timestampMs >= now - 60d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no matches in window.", featureGroup: "team-recent-form" },
  { key: "Last60DayWinRate", type: "numeric", description: "Win rate over the trailing 60 calendar days.", sourceFields: ["matches.scheduledAt", "matches.winnerId"], transformation: "wins / count over the 60-day window.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when the window is empty.", featureGroup: "team-recent-form" },
  { key: "RecentMapWinRateLast10", type: "numeric", description: "Map win rate across the last 10 matches.", sourceFields: ["matches.maps"], transformation: "mapsWon / (mapsWon+mapsLost) over last 10 matches.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when no maps in window.", featureGroup: "team-recent-form" },
  { key: "RecentAvgMapsWonLast10", type: "numeric", description: "Average maps won per match over the last 10 matches.", sourceFields: ["matches.maps"], transformation: "average(mapsWon) over last 10 matches.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when the window is empty.", featureGroup: "team-recent-form" },
  { key: "RecentAvgMapsLostLast10", type: "numeric", description: "Average maps lost per match over the last 10 matches.", sourceFields: ["matches.maps"], transformation: "average(mapsLost) over last 10 matches.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when the window is empty.", featureGroup: "team-recent-form" },
  { key: "FormTrend", type: "numeric", description: "Simple momentum signal: last-5 win rate minus last-10 win rate.", sourceFields: ["matches.winnerId"], transformation: "last5WinRate - last10WinRate.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when both windows use the same 0.5 cold-start prior.", featureGroup: "team-recent-form" },
];

const RATING_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "EloRating", type: "numeric", description: "Pre-match Elo rating (baseline feature signal, not a production model) — see docs/32 for configuration.", sourceFields: ["matches.winnerId", "matches.teamAId/teamBId"], transformation: "Standard Elo update, binary win/loss, no margin-of-victory multiplier.", temporalAvailabilityRule: "Exported strictly before this match's own Elo update is applied.", missingValuePolicy: "Configured initial rating (1500) for an unseen team.", featureGroup: "rating" },
  { key: "EloWinProbability", type: "numeric", description: "Elo-implied win probability against this specific opponent's pre-match rating.", sourceFields: ["EloRating (both teams)"], transformation: "1 / (1 + 10^((opponentRating-ownRating)/400)).", temporalAvailabilityRule: "Uses only pre-match ratings for both teams.", missingValuePolicy: "0.5 when both teams are at the initial rating.", featureGroup: "rating" },
];

const OPPONENT_STRENGTH_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "AvgOpponentEloLast5", type: "numeric", description: "Average pre-match Elo of the last 5 opponents faced, frozen at the time each encounter happened.", sourceFields: ["matches.teamBId/teamAId"], transformation: "average(opponentEloAtEncounter) over last 5.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Initial rating (1500) fallback when no history.", featureGroup: "opponent-strength" },
  { key: "AvgOpponentEloLast10", type: "numeric", description: "Average pre-match Elo of the last 10 opponents faced.", sourceFields: ["matches.teamBId/teamAId"], transformation: "average(opponentEloAtEncounter) over last 10.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Initial rating (1500) fallback when no history.", featureGroup: "opponent-strength" },
  { key: "AvgOpponentWinRateLast5", type: "numeric", description: "Average cumulative win rate of the last 5 opponents, as it stood at the time each was faced.", sourceFields: ["matches.winnerId"], transformation: "average(opponentWinRateAtEncounter) over last 5.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 fallback when no history.", featureGroup: "opponent-strength" },
  { key: "AvgOpponentWinRateLast10", type: "numeric", description: "Average cumulative win rate of the last 10 opponents, as it stood at the time each was faced.", sourceFields: ["matches.winnerId"], transformation: "average(opponentWinRateAtEncounter) over last 10.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 fallback when no history.", featureGroup: "opponent-strength" },
  { key: "StrengthOfScheduleAllTime", type: "numeric", description: "Average pre-match Elo of every opponent faced across career history.", sourceFields: ["matches.teamBId/teamAId"], transformation: "average(opponentEloAtEncounter) over all matchHistory.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Initial rating (1500) fallback when no history.", featureGroup: "opponent-strength" },
  { key: "WinsVsAboveMedianOpponentCount", type: "integer", description: "Career wins against opponents whose frozen pre-match Elo exceeded the dataset-wide running median at the time of the encounter.", sourceFields: ["matches.winnerId"], transformation: "Count of matchHistory entries won && opponentAboveMedianAtEncounter.", temporalAvailabilityRule: "Median is computed strictly from observations before the current timestamp group; never recomputed retroactively.", missingValuePolicy: "0 when no history.", featureGroup: "opponent-strength" },
  { key: "LossesVsBelowMedianOpponentCount", type: "integer", description: "Career losses against opponents whose frozen pre-match Elo was below the dataset-wide running median at the time of the encounter.", sourceFields: ["matches.winnerId"], transformation: "Count of matchHistory entries lost && !opponentAboveMedianAtEncounter.", temporalAvailabilityRule: "Median is computed strictly from observations before the current timestamp group.", missingValuePolicy: "0 when no history.", featureGroup: "opponent-strength" },
];

const MAP_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "MapPoolBreadth", type: "integer", description: "Distinct recognized maps this team has played historically.", sourceFields: ["matches.maps.map"], transformation: "Count of distinct recognized map names in mapStats.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no maps played.", featureGroup: "map-history" },
  { key: "TopMapConcentration", type: "numeric", description: "Share of recognized maps played that fall on this team's single most-played map.", sourceFields: ["matches.maps.map"], transformation: "max(played per map) / total recognized maps played.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no maps played.", featureGroup: "map-history" },
  { key: "MapExperienceEntropy", type: "numeric", description: "Normalized Shannon entropy (0-1) of the team's recognized-map distribution — a simple map-pool diversity measure.", sourceFields: ["matches.maps.map"], transformation: "-sum(p*log2 p) / log2(distinctMapCount).", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when 0 or 1 distinct maps played.", featureGroup: "map-history" },
  { key: "UnknownMapCount", type: "integer", description: "Count of played map instances on an unrecognized (not-yet-catalogued) map name.", sourceFields: ["matches.maps.map.recognized"], transformation: "Count of played instances where map.recognized === false.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none observed.", featureGroup: "map-history" },
  { key: "AvgRoundsWonPerMap", type: "numeric", description: "Average rounds won per played map (recognized or unknown; unplayed placeholders always excluded).", sourceFields: ["matches.maps.teamAScore/teamBScore"], transformation: "roundsWonTotal / totalMapsPlayed.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no maps played.", featureGroup: "map-history" },
  { key: "AvgRoundsLostPerMap", type: "numeric", description: "Average rounds lost per played map.", sourceFields: ["matches.maps.teamAScore/teamBScore"], transformation: "roundsLostTotal / totalMapsPlayed.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no maps played.", featureGroup: "map-history" },
  { key: "HasAttackDefenseSplitData", type: "boolean", description: "True when at least one historical map instance carried attack/defense round-split data.", sourceFields: ["matches.maps.teamAAttackScore/teamADefenseScore"], transformation: "attackRoundsPlayedTotal > 0 || defenseRoundsPlayedTotal > 0.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Not applicable — always defined.", featureGroup: "map-history" },
  { key: "AttackSideWinRate", type: "numeric", description: "Round win rate while on the attacking side, reconstructed as (own attack rounds won) / (own attack rounds won + opponent's defense rounds won in the same half).", sourceFields: ["matches.maps.teamAAttackScore", "matches.maps.teamBDefenseScore (opponent perspective)"], transformation: "attackRoundsWonTotal / attackRoundsPlayedTotal.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when no split data exists (see HasAttackDefenseSplitData).", featureGroup: "map-history" },
  { key: "DefenseSideWinRate", type: "numeric", description: "Round win rate while on the defending side, reconstructed analogously to AttackSideWinRate.", sourceFields: ["matches.maps.teamADefenseScore", "matches.maps.teamBAttackScore (opponent perspective)"], transformation: "defenseRoundsWonTotal / defenseRoundsPlayedTotal.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior when no split data exists.", featureGroup: "map-history" },
];

const SCHEDULE_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "DaysSinceLastMatch", type: "numeric", description: "Days elapsed since this team's previous completed match.", sourceFields: ["matches.scheduledAt"], transformation: "(now - lastMatchMs) / 86400000.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "null (see HasPriorMatch) for a team's first match — explicit cold start, never fabricated.", featureGroup: "schedule-rest" },
  { key: "HasPriorMatch", type: "boolean", description: "Explicit missingness indicator for DaysSinceLastMatch/HoursSinceLastMatch.", sourceFields: ["matches"], transformation: "matchHistory.length > 0.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Not applicable — always defined.", featureGroup: "schedule-rest" },
  { key: "HoursSinceLastMatch", type: "numeric", description: "Hours elapsed since this team's previous completed match.", sourceFields: ["matches.scheduledAt"], transformation: "(now - lastMatchMs) / 3600000.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "null for a team's first match.", featureGroup: "schedule-rest" },
  { key: "MatchesLast7Days", type: "integer", description: "Matches played in the trailing 7 calendar days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where timestampMs >= now - 7d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "MatchesLast14Days", type: "integer", description: "Matches played in the trailing 14 calendar days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where timestampMs >= now - 14d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "MatchesLast30Days", type: "integer", description: "Matches played in the trailing 30 calendar days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where timestampMs >= now - 30d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "MapsLast7Days", type: "integer", description: "Maps played in the trailing 7 calendar days.", sourceFields: ["matches.maps", "matches.scheduledAt"], transformation: "Sum of mapsWon+mapsLost for matches in the 7-day window.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "MapsLast14Days", type: "integer", description: "Maps played in the trailing 14 calendar days.", sourceFields: ["matches.maps", "matches.scheduledAt"], transformation: "Sum of mapsWon+mapsLost for matches in the 14-day window.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "MapsLast30Days", type: "integer", description: "Maps played in the trailing 30 calendar days.", sourceFields: ["matches.maps", "matches.scheduledAt"], transformation: "Sum of mapsWon+mapsLost for matches in the 30-day window.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "IsBackToBack", type: "boolean", description: "True when less than 24 hours elapsed since this team's previous match.", sourceFields: ["matches.scheduledAt"], transformation: "DaysSinceLastMatch !== null && DaysSinceLastMatch < 1.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "false for a team's first match (no prior match to compare against).", featureGroup: "schedule-rest" },
  { key: "SameDayMatchCountBeforeGroup", type: "integer", description: "Matches already played by this team on the same UTC calendar day as the current match, strictly before this timestamp group.", sourceFields: ["matches.scheduledAt"], transformation: "Count of matchHistory entries sharing the current match's UTC date.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", featureGroup: "schedule-rest" },
  { key: "InactivityFlag", type: "boolean", description: "True when more than 30 days elapsed since this team's previous match.", sourceFields: ["matches.scheduledAt"], transformation: "DaysSinceLastMatch !== null && DaysSinceLastMatch > 30.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "false for a team's first match (cold start, not inactivity).", featureGroup: "schedule-rest" },
];

const ROSTER_FIELDS: readonly TeamFieldTemplate[] = [
  { key: "RosterSnapshotAvailable", type: "boolean", description: "True when this match recorded a non-empty roster snapshot for this team.", sourceFields: ["matches.rosterSnapshots"], transformation: "rosterPlayerIds !== null && length > 0.", temporalAvailabilityRule: "Known at match time from the match's own roster snapshot.", missingValuePolicy: "false when no snapshot exists — never assumed complete.", featureGroup: "roster-player" },
  { key: "RosterSize", type: "integer", description: "Number of players in this match's roster snapshot for this team.", sourceFields: ["matches.rosterSnapshots"], transformation: "rosterPlayerIds.length.", temporalAvailabilityRule: "Known at match time.", missingValuePolicy: "0 when unavailable.", featureGroup: "roster-player" },
  { key: "PlayersWithPriorTeamAppearanceCount", type: "integer", description: "Number of the current roster's players who have appeared for this specific team before.", sourceFields: ["roster-appearances"], transformation: "Count of current roster IDs found in this team's rosterHistory.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterContinuityVsPreviousMatch", type: "numeric", description: "Jaccard overlap between the current roster and this team's immediately-previous observed roster.", sourceFields: ["roster-appearances"], transformation: "|current ∩ previous| / |current ∪ previous|.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when no previous roster or current roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterContinuityLast3Matches", type: "numeric", description: "Fraction of the current roster that appeared in any of this team's last 3 observed rosters.", sourceFields: ["roster-appearances"], transformation: "overlap-with-union(last 3 rosters) / current roster size.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "SharedPriorMatchesAmongRosterAvg", type: "numeric", description: "Average, over all current-roster player pairs, of prior matches both played together for this team.", sourceFields: ["roster-appearances"], transformation: "average over C(k,2) pairs of a per-pair shared-match counter.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable or has fewer than 2 players.", featureGroup: "roster-player" },
  { key: "RosterAvgPlayerPriorAppearances", type: "numeric", description: "Average career prior appearances (any team) across the current roster.", sourceFields: ["roster-appearances"], transformation: "average(player.priorAppearanceCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterMinPlayerPriorAppearances", type: "integer", description: "Minimum career prior appearances across the current roster.", sourceFields: ["roster-appearances"], transformation: "min(player.priorAppearanceCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterMaxPlayerPriorAppearances", type: "integer", description: "Maximum career prior appearances across the current roster.", sourceFields: ["roster-appearances"], transformation: "max(player.priorAppearanceCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterDebutingPlayerCount", type: "integer", description: "Number of current-roster players with zero prior appearances anywhere in the curated dataset.", sourceFields: ["roster-appearances"], transformation: "Count of roster players where player.hasAppeared() is false.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "DaysSinceRosterLastAppearedTogether", type: "numeric", description: "Days since this exact 5-player roster set last appeared together for this team.", sourceFields: ["roster-appearances"], transformation: "(now - lastSeenMs(rosterSetKey)) / 86400000.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "null when this roster set has never been observed before, or roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterAvgPlayerPriorWins", type: "numeric", description: "Average career prior match wins across the current roster.", sourceFields: ["roster-appearances", "matches.winnerId"], transformation: "average(player.priorWinCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterAvgPlayerRecentAppearances30Days", type: "numeric", description: "Average appearances in the trailing 30 days across the current roster.", sourceFields: ["roster-appearances"], transformation: "average(player.priorAppearancesSince(now-30d)) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterPriorInternationalAppearances", type: "integer", description: "Total prior appearances at international-tier (Masters/Champions-level tournamentLevel) events, summed across the current roster.", sourceFields: ["roster-appearances", "events.tournamentLevel"], transformation: "sum(player.priorInternationalAppearanceCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
  { key: "RosterPriorMastersChampionsAppearances", type: "integer", description: "Total prior appearances specifically at Masters/Champions events, summed across the current roster.", sourceFields: ["roster-appearances", "events.eventFamily"], transformation: "sum(player.priorMastersChampionsAppearanceCount) over roster.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when roster unavailable.", featureGroup: "roster-player" },
];

const TEAM_FIELD_TEMPLATES: readonly TeamFieldTemplate[] = [...CUMULATIVE_FIELDS, ...RECENT_FORM_FIELDS, ...RATING_FIELDS, ...OPPONENT_STRENGTH_FIELDS, ...MAP_FIELDS, ...SCHEDULE_FIELDS, ...ROSTER_FIELDS];

function buildTeamCatalog(prefix: "teamA" | "teamB"): FeatureFieldMeta[] {
  const sideNote = prefix === "teamA" ? "Team A." : "Team B.";
  return TEAM_FIELD_TEMPLATES.map((t) => ({
    name: `${prefix}${t.key}`,
    type: t.type,
    description: `${sideNote} ${t.description}`,
    sourceFields: t.sourceFields,
    transformation: t.transformation,
    temporalAvailabilityRule: t.temporalAvailabilityRule,
    missingValuePolicy: t.missingValuePolicy,
    leakageRisk: "none" as const,
    featureGroup: t.featureGroup,
    versionIntroduced: V,
  }));
}

const IDENTIFIER_FIELDS: readonly FeatureFieldMeta[] = [
  { name: "matchInternalId", type: "identifier", description: "Deterministic internal match ID (vlr:match:<id>).", sourceFields: ["matches.internalId"], transformation: "Passthrough.", temporalAvailabilityRule: "Known at match creation.", missingValuePolicy: "Never missing — a validation error otherwise.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "providerMatchId", type: "identifier", description: "Raw VLR provider match ID.", sourceFields: ["matches.sourceReference.externalId"], transformation: "Passthrough.", temporalAvailabilityRule: "Known at match creation.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "scheduledAt", type: "identifier", description: "Normalized ISO 8601 scheduled timestamp.", sourceFields: ["matches.scheduledAt.iso"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff (it's the schedule itself).", missingValuePolicy: "A match with a null scheduledAt.iso is rejected before feature generation, never included.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "eventInternalId", type: "identifier", description: "Deterministic internal event ID.", sourceFields: ["matches.eventId"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "eventFamily", type: "categorical", description: "Approved event family (vct-americas/emea/pacific/china, masters, champions).", sourceFields: ["events.eventFamily"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing — curation only includes approved families.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "eventRegion", type: "categorical", description: "Tournament region, or the explicit \"unknown\" category for international events with no region tag.", sourceFields: ["events.region"], transformation: "Passthrough, defaulted to \"unknown\".", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Explicit \"unknown\" category — never guessed.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "eventStage", type: "categorical", description: "Tournament stage label, or \"unknown\".", sourceFields: ["events.stage"], transformation: "Passthrough, defaulted to \"unknown\".", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Explicit \"unknown\" category.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "tournamentLevel", type: "categorical", description: "\"international\" or \"league\".", sourceFields: ["events.tournamentLevel"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "seriesFormat", type: "categorical", description: "Best-of format (bo1/bo3/bo5/unknown).", sourceFields: ["matches.seriesFormat"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Explicit \"unknown\" category when the source format couldn't be normalized.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "teamAProviderId", type: "identifier", description: "Provider identity of the match's team A, in its recorded orientation.", sourceFields: ["matches.teamAId"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "teamBProviderId", type: "identifier", description: "Provider identity of the match's team B, in its recorded orientation.", sourceFields: ["matches.teamBId"], transformation: "Passthrough.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "identifier", versionIntroduced: V },
  { name: "sourceDatasetVersion", type: "version", description: "TASK-043 curated dataset version this row was built from.", sourceFields: ["dataset-manifest.json.curatedDatasetVersion"], transformation: "Passthrough.", temporalAvailabilityRule: "Not match-specific — a build-time constant.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "lineage", versionIntroduced: V },
  { name: "featureSchemaVersion", type: "version", description: "Version of this canonical feature-row schema.", sourceFields: ["versions.ts"], transformation: "Constant.", temporalAvailabilityRule: "Build-time constant.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "lineage", versionIntroduced: V },
  { name: "featureRulesVersion", type: "version", description: "Version of the feature-computation rules that produced this row.", sourceFields: ["versions.ts"], transformation: "Constant.", temporalAvailabilityRule: "Build-time constant.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "lineage", versionIntroduced: V },
];

const MATCH_LEVEL_FIELDS: readonly FeatureFieldMeta[] = [
  { name: "eloRatingDiff", type: "numeric", description: "teamAEloRating minus teamBEloRating.", sourceFields: ["teamAEloRating", "teamBEloRating"], transformation: "Subtraction.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when both teams are at the initial rating.", leakageRisk: "none", featureGroup: "rating", versionIntroduced: V },
  { name: "eloRatingVersion", type: "version", description: "Elo configuration/rules version used to compute every rating field in this row.", sourceFields: ["versions.ts DEFAULT_ELO_CONFIG"], transformation: "Constant per build.", temporalAvailabilityRule: "Build-time constant.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "lineage", versionIntroduced: V },
  { name: "knownMapPoolOverlapCount", type: "integer", description: "Number of recognized maps both teams have historical experience on (aggregate map-pool feature — never the current match's own map selection).", sourceFields: ["team map histories"], transformation: "|teamA recognized maps ∩ teamB recognized maps|.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when either team has no map history.", leakageRisk: "none", featureGroup: "map-history", versionIntroduced: V },
  { name: "mapStrengthDifferential", type: "numeric", description: "teamACumulativeMapWinRate minus teamBCumulativeMapWinRate.", sourceFields: ["teamACumulativeMapWinRate", "teamBCumulativeMapWinRate"], transformation: "Subtraction.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when both teams use the 0.5 cold-start prior.", leakageRisk: "none", featureGroup: "map-history", versionIntroduced: V },
  { name: "h2hPriorMeetingCount", type: "integer", description: "Prior meetings between these two teams (in either orientation).", sourceFields: ["matches.teamAId/teamBId (unordered pair)"], transformation: "Count of stored H2H records for this unordered pair.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hTeamAWins", type: "integer", description: "Prior meetings this match's team A has won.", sourceFields: ["matches.winnerId"], transformation: "Count of H2H records won by the current teamAProviderId.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hTeamBWins", type: "integer", description: "Prior meetings this match's team B has won.", sourceFields: ["matches.winnerId"], transformation: "Count of H2H records won by the current teamBProviderId.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hTeamAWinRate", type: "numeric", description: "Team A's win rate across all prior meetings between these two teams.", sourceFields: ["matches.winnerId"], transformation: "h2hTeamAWins / h2hPriorMeetingCount.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Neutral 0.5 prior for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hPriorMapDifferential", type: "integer", description: "Net maps won by team A minus team B across all prior meetings, oriented to the current match's team A/B.", sourceFields: ["matches.maps"], transformation: "Sum of (orientedMapsA - orientedMapsB) across H2H records.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMeetingsLast90Days", type: "integer", description: "Prior meetings within the trailing 90 days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where ageMs <= 90d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMeetingsLast180Days", type: "integer", description: "Prior meetings within the trailing 180 days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where ageMs <= 180d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMeetingsLast365Days", type: "integer", description: "Prior meetings within the trailing 365 days.", sourceFields: ["matches.scheduledAt"], transformation: "Count where ageMs <= 365d.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMostRecentMeetingWinnerProviderId", type: "categorical", description: "Provider ID of the winner of the most recent prior meeting, or the explicit \"unknown\" category.", sourceFields: ["matches.winnerId"], transformation: "Last H2H record's winnerTeamId.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "Explicit \"unknown\" for a first-ever meeting.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMeetingsSameEventFamily", type: "integer", description: "Prior meetings that took place within the same event family as the current match.", sourceFields: ["events.eventFamily"], transformation: "Count of H2H records where eventFamily matches.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "h2hMeetingsSameEventRegion", type: "integer", description: "Prior meetings that took place within the same event region as the current match (only counted when the current region is known).", sourceFields: ["events.region"], transformation: "Count of H2H records where eventRegion matches, skipped if current region is \"unknown\".", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none or current region unknown.", leakageRisk: "none", featureGroup: "head-to-head", versionIntroduced: V },
  { name: "restDifferenceDays", type: "numeric", description: "teamADaysSinceLastMatch minus teamBDaysSinceLastMatch.", sourceFields: ["teamADaysSinceLastMatch", "teamBDaysSinceLastMatch"], transformation: "Subtraction.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "null when either team has no prior match.", leakageRisk: "none", featureGroup: "schedule-rest", versionIntroduced: V },
  { name: "eventStageMatchesLast3Days", type: "integer", description: "Matches already played under this same event, in the trailing 3 days before this match — a simple tournament-congestion signal.", sourceFields: ["matches.eventId", "matches.scheduledAt"], transformation: "Count of prior matches under the same eventInternalId within 3 days.", temporalAvailabilityRule: PRE_GROUP_RULE, missingValuePolicy: "0 when none.", leakageRisk: "none", featureGroup: "schedule-rest", versionIntroduced: V },
  { name: "seasonYear", type: "integer", description: "UTC calendar year of the match's scheduled timestamp.", sourceFields: ["matches.scheduledAt"], transformation: "Date.getUTCFullYear().", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "matchMonth", type: "integer", description: "UTC calendar month (1-12) of the match's scheduled timestamp.", sourceFields: ["matches.scheduledAt"], transformation: "Date.getUTCMonth() + 1.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "isInternationalEvent", type: "boolean", description: "True when tournamentLevel is \"international\".", sourceFields: ["events.tournamentLevel"], transformation: "Equality check.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "isRegionalLeague", type: "boolean", description: "True when tournamentLevel is \"league\".", sourceFields: ["events.tournamentLevel"], transformation: "Equality check.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
  { name: "isMastersOrChampions", type: "boolean", description: "True when eventFamily is \"masters\" or \"champions\".", sourceFields: ["events.eventFamily"], transformation: "Set membership check.", temporalAvailabilityRule: "Known before kickoff.", missingValuePolicy: "Never missing.", leakageRisk: "none", featureGroup: "event-context", versionIntroduced: V },
];

const LABEL_FIELDS: readonly FeatureFieldMeta[] = [
  { name: "labelTeamAWin", type: "label", description: "Binary target: 1 if team A won, 0 if team B won.", sourceFields: ["matches.winnerId"], transformation: "winnerId === teamAId ? 1 : 0.", temporalAvailabilityRule: "Post-match only — never a feature input.", missingValuePolicy: "A match with no valid winner is rejected, never given a fabricated label.", leakageRisk: "none", featureGroup: "label", versionIntroduced: V },
  { name: "labelWinnerProviderId", type: "label", description: "Provider ID of the winning team.", sourceFields: ["matches.winnerId"], transformation: "Passthrough.", temporalAvailabilityRule: "Post-match only.", missingValuePolicy: "Never missing for an included row.", leakageRisk: "none", featureGroup: "label", versionIntroduced: V },
  { name: "labelSeriesScore", type: "label", description: "Maps won by team A and team B, formatted \"<A>-<B>\", counting only actually-played maps.", sourceFields: ["matches.maps"], transformation: "`${teamAMapWins}-${teamBMapWins}`.", temporalAvailabilityRule: "Post-match only.", missingValuePolicy: "Never missing for an included row.", leakageRisk: "none", featureGroup: "label", versionIntroduced: V },
  { name: "labelMapCountPlayed", type: "label", description: "Total maps actually played in this match (excludes unplayed placeholders/deciders).", sourceFields: ["matches.maps"], transformation: "Count of maps passing isMapActuallyPlayed.", temporalAvailabilityRule: "Post-match only.", missingValuePolicy: "Never missing for an included row.", leakageRisk: "none", featureGroup: "label", versionIntroduced: V },
];

export const FEATURE_CATALOG: readonly FeatureFieldMeta[] = [...IDENTIFIER_FIELDS, ...buildTeamCatalog("teamA"), ...buildTeamCatalog("teamB"), ...MATCH_LEVEL_FIELDS, ...LABEL_FIELDS];

export function featureCatalogFieldNames(): readonly string[] {
  return FEATURE_CATALOG.map((f) => f.name);
}

const NON_FEATURE_GROUPS: ReadonlySet<string> = new Set(["identifier", "label", "lineage"]);

/** Count of actual model-input feature columns — excludes identifiers, lineage/version constants, and labels. */
export function countFeatureFields(): number {
  return FEATURE_CATALOG.filter((f) => !NON_FEATURE_GROUPS.has(f.featureGroup)).length;
}

/** Human-readable summary, grouped by feature group — used by `pnpm ingest:vlr:features:catalog`. */
export function formatFeatureCatalogReport(): string {
  const byGroup = new Map<string, FeatureFieldMeta[]>();
  for (const field of FEATURE_CATALOG) {
    const bucket = byGroup.get(field.featureGroup) ?? [];
    bucket.push(field);
    byGroup.set(field.featureGroup, bucket);
  }
  const lines: string[] = [`Feature catalog — ${FEATURE_CATALOG.length} fields, schema ${FEATURE_SCHEMA_VERSION}, rules ${FEATURE_RULES_VERSION}`, ""];
  for (const [group, fields] of [...byGroup.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`## ${group} (${fields.length})`);
    for (const field of fields) lines.push(`  - ${field.name} [${field.type}]: ${field.description}`);
    lines.push("");
  }
  return lines.join("\n");
}
