import type { ContributionRow, DnaGapRow } from "./types";

/**
 * TASK-037 explicit mapping layer (requirement 7). `KeyFactor.id` is
 * generated by the engine as literally the source `DnaDimensionKey` string
 * (`services/prediction-engine/src/lib/insights.ts:37`), and Contribution
 * rows carry that same id through unchanged — so a key factor, its
 * contribution row, and its Team DNA dimension are the same entity
 * identified by the same key. These are exact-match lookups, not fuzzy
 * heuristics: if no row/dimension shares the id, the mapping deterministically
 * returns null rather than guessing at a related item.
 */
export function findContributionForFactor(
  factorId: string,
  contributions: readonly ContributionRow[],
): ContributionRow | null {
  return contributions.find((row) => row.id === factorId) ?? null;
}

export function findDnaDimensionForFactor(factorId: string, dnaRows: readonly DnaGapRow[]): DnaGapRow | null {
  return dnaRows.find((row) => row.key === factorId) ?? null;
}
