import type { CurrentPredictionResponse } from "@repo/shared";
import { expectedWinProbabilityFromElo } from "./eloFormula";

const FIXTURE_TEAM_A_ELO = 1550;
const FIXTURE_TEAM_B_ELO = 1480;
// Computed from the real formula (not hand-typed) so a zero-delta simulation
// reproduces the baseline exactly, matching how the real elo-baseline
// estimator (calibrationMethod: "none") actually behaves.
const FIXTURE_TEAM_A_WIN_PROBABILITY = expectedWinProbabilityFromElo(FIXTURE_TEAM_A_ELO, FIXTURE_TEAM_B_ELO);

/** Shared fixture for `presentationAdapter.test.ts` and `simulate.test.ts` — a realistic, fully-populated `CurrentPredictionResponse` (mirrors the shape `currentPredictionAdapter.ts` actually returns). */
export function buildFixtureResponse(overrides: Partial<CurrentPredictionResponse> = {}): CurrentPredictionResponse {
  return {
    mode: "current-real-model",
    requestId: "req-1",
    teamAId: "team-a",
    teamBId: "team-b",
    seriesFormat: "BO3",
    tournamentTier: "league",
    eventRegion: "americas",
    modelVersion: "fixture-model-v1",
    estimatorType: "elo-baseline",
    calibrationMethod: "none",
    teamAWinProbability: FIXTURE_TEAM_A_WIN_PROBABILITY,
    teamBWinProbability: 1 - FIXTURE_TEAM_A_WIN_PROBABILITY,
    predictedWinnerSide: "teamA",
    confidence: Math.abs(FIXTURE_TEAM_A_WIN_PROBABILITY - 0.5) * 2,
    warnings: [],
    predictionGeneratedAt: "2026-07-24T00:00:00.000Z",
    inferenceDurationMs: 0.6,
    dataProvenance: {
      sourceFeatureDatasetVersion: "fixture-feature-dataset-v1",
      featureSchemaVersion: "fixture-feature-schema@1.0.0",
      canonicalWindowStartIso: "2025-06-07T12:00:00.000Z",
      modelTrainDateRangeEndIso: "2026-04-24T11:00:00.000Z",
      asOfIso: "2026-07-18T04:00:00.000Z",
      constructedFromRealFeatureData: true,
    },
    teamAConfidence: { teamId: "team-a", confidence: "verified", seriesCountInWindow: 30 },
    teamBConfidence: { teamId: "team-b", confidence: "verified", seriesCountInWindow: 25 },
    teamAState: {
      teamId: "team-a",
      isColdStart: false,
      eloRating: FIXTURE_TEAM_A_ELO,
      recentFormWinRate: 0.6,
      formTrend: 0.05,
      opponentAdjustedRating: 1500,
      strengthOfSchedule: 1480,
      mapPoolBreadth: 7,
      recentMapWinRate: 0.55,
      avgRoundsWonPerMap: 13,
      avgRoundsLostPerMap: 10,
      daysSinceLastMatch: 5,
      isBackToBack: false,
      priorInternationalAppearances: 3,
      priorMastersChampionsAppearances: 1,
      seriesCountInWindow: 30,
    },
    teamBState: {
      teamId: "team-b",
      isColdStart: false,
      eloRating: FIXTURE_TEAM_B_ELO,
      recentFormWinRate: 0.5,
      formTrend: -0.02,
      opponentAdjustedRating: 1470,
      strengthOfSchedule: 1460,
      mapPoolBreadth: 6,
      recentMapWinRate: 0.5,
      avgRoundsWonPerMap: 12,
      avgRoundsLostPerMap: 11,
      daysSinceLastMatch: 8,
      isBackToBack: false,
      priorInternationalAppearances: 2,
      priorMastersChampionsAppearances: 0,
      seriesCountInWindow: 25,
    },
    contribution: {
      driverLabel: "Elo rating differential",
      driverDifferential: FIXTURE_TEAM_A_ELO - FIXTURE_TEAM_B_ELO,
      uncalibratedProbability: FIXTURE_TEAM_A_WIN_PROBABILITY,
      calibrationAdjustment: 0,
      finalProbability: FIXTURE_TEAM_A_WIN_PROBABILITY,
      isSoleDriver: true,
    },
    supportingContext: [
      { id: "recent-form", label: "Recent Form", favoredSide: "teamA", teamAValue: 0.6, teamBValue: 0.5, description: "Win rate across each team's last 10 real matches.", isDirectModelInput: false },
      { id: "opponent-adjusted-strength", label: "Opponent-Adjusted Strength", favoredSide: "teamA", teamAValue: 1500, teamBValue: 1470, description: "Average real opponent Elo faced in each team's last 10 matches.", isDirectModelInput: false },
      { id: "map-pool-breadth", label: "Map Pool Breadth", favoredSide: "teamA", teamAValue: 7, teamBValue: 6, description: "Count of distinct real maps each team has recorded matches on.", isDirectModelInput: false },
      { id: "schedule-strength", label: "Strength of Schedule", favoredSide: "teamA", teamAValue: 1480, teamBValue: 1460, description: "Average real opponent Elo across each team's entire match history.", isDirectModelInput: false },
      { id: "activity-rest", label: "Activity & Rest", favoredSide: "teamA", teamAValue: 5, teamBValue: 8, description: "Days since each team's last real match.", isDirectModelInput: false },
      { id: "competition-experience", label: "Competition Experience", favoredSide: "teamA", teamAValue: 4, teamBValue: 2, description: "Combined real prior International/Masters/Champions roster appearances.", isDirectModelInput: false },
    ],
    evidenceTrust: {
      score: 78,
      explanation: "30 real series for team A and 25 for team B in the canonical data window.",
      teamASeriesCount: 30,
      teamBSeriesCount: 25,
      teamAIdentityConfidence: "verified",
      teamBIdentityConfidence: "verified",
      h2hMeetingCount: 2,
    },
    headToHead: { priorMeetingCount: 2, teamAWins: 1, teamBWins: 1, teamAWinRate: 0.5, priorMapDifferential: 0, meetingsLast365Days: 2 },
    mapEvidence: {
      teamAMapPoolBreadth: 7,
      teamBMapPoolBreadth: 6,
      teamARecentMapWinRate: 0.55,
      teamBRecentMapWinRate: 0.5,
      teamACumulativeMapWinRate: 0.52,
      teamBCumulativeMapWinRate: 0.48,
      teamAAvgRoundsWonPerMap: 13,
      teamBAvgRoundsWonPerMap: 12,
      teamAAvgRoundsLostPerMap: 10,
      teamBAvgRoundsLostPerMap: 11,
      knownMapPoolOverlapCount: 5,
      mapStrengthDifferential: 0.04,
      evidenceLevel: "sufficient",
    },
    pipeline: [
      { id: "match-request", label: "Match Request", description: "Received the selected teams, series format, and tournament tier.", durationMs: null },
      { id: "load-curated-data", label: "Load Curated Match Data", description: "Loaded the real curated match and event dataset as of the canonical data cutoff.", durationMs: null },
      { id: "run-estimator", label: "Run Selected Estimator", description: "Scored the encoded row with the currently selected estimator.", durationMs: 0.6 },
      { id: "generate-explanation", label: "Generate Human-Readable Explanation", description: "Built the deterministic explanation.", durationMs: null },
    ],
    ...overrides,
  };
}
