/**
 * Central registry for the produced media library at `public/assets/`.
 * Every file used anywhere in the app resolves through this manifest instead
 * of a hardcoded path, so a section always knows an asset's stable URL,
 * intrinsic size (for layout-shift-free rendering), and intended purpose.
 *
 * Width/height are the source files' real pixel dimensions for images
 * (extracted from the PNG headers). Videos reuse the library's dominant
 * cinematic ratio, or their paired still's exact ratio where one exists —
 * used only to size the CSS aspect-ratio box, not for next/image sizing.
 */

export type MediaType = "image" | "video";

export type MediaRole = "background" | "inset" | "watermark" | "reserved";

export interface MediaAsset {
  id: string;
  path: string;
  type: MediaType;
  width: number;
  height: number;
  section: string;
  role: MediaRole;
  integrated: boolean;
  /** Required when integrated is false — why this asset isn't wired in yet. */
  note?: string;
}

export const MEDIA_ASSETS = {
  heroVideoLoop: {
    id: "hero-video-loop",
    path: "/assets/01-hero-video-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "landing.hero",
    role: "background",
    integrated: true,
  },
  heroFallbackImage: {
    id: "hero-fallback-image",
    path: "/assets/02-hero-fallback-image.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "landing.hero",
    role: "background",
    integrated: true,
  },
  productStory: {
    id: "product-story",
    path: "/assets/03-product-story.png",
    type: "image",
    width: 2752,
    height: 1536,
    section: "landing.productStory",
    role: "inset",
    integrated: true,
  },
  productStoryLoop: {
    id: "product-story-loop",
    path: "/assets/04-product-story-loop.mp4",
    type: "video",
    width: 2752,
    height: 1536,
    section: "landing.productStory",
    role: "reserved",
    integrated: false,
    note: "Alternate motion treatment for the same slot as product-story — the static still already carries the section, a second looping layer here would stack motion without adding information.",
  },
  teamDna: {
    id: "team-dna",
    path: "/assets/05-team-dna.png",
    type: "image",
    width: 1536,
    height: 2752,
    section: "matchDna.teamDnaCard",
    role: "watermark",
    integrated: true,
  },
  matchDna: {
    id: "match-dna",
    path: "/assets/06-match-dna.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "matchDna.section",
    role: "inset",
    integrated: true,
  },
  analyticsDashboard: {
    id: "analytics-dashboard",
    path: "/assets/07-analytics-dashboard.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "landing.coreFeatures",
    role: "background",
    integrated: true,
  },
  predictionStudioDashboard: {
    id: "prediction-studio-dashboard",
    path: "/assets/08-prediction-studio-dashboard.png",
    type: "image",
    width: 2752,
    height: 1536,
    section: "landing.predictionStudioPreview",
    role: "inset",
    integrated: true,
  },
  teamComparison: {
    id: "team-comparison",
    path: "/assets/09-team-comparison.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "teamComparison.page",
    role: "inset",
    integrated: true,
  },
  matchDnaCore: {
    id: "match-dna-core",
    path: "/assets/10-match-dna-core.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "matchDna.summary",
    role: "reserved",
    integrated: false,
    note: "Reserved for a possible future MatchDnaSummary illustration — the section banner (match-dna asset) already carries this section's imagery this pass.",
  },
  featureContribution: {
    id: "feature-contribution",
    path: "/assets/11-feature-contribution.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "insights.keyFactorsList",
    role: "reserved",
    integrated: false,
    note: "KeyFactorsList renders real per-factor data — decorative artwork per factor would compete with the real chart, so this stays reserved.",
  },
  confidenceEngine: {
    id: "confidence-engine",
    path: "/assets/12-confidence-engine.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "insights.explanationCard",
    role: "reserved",
    integrated: false,
    note: "ExplanationCard renders real explanation data — reserved rather than layered behind live reasoning text.",
  },
  trustScore: {
    id: "trust-score",
    path: "/assets/13-trust-score.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "predictionStudio.probabilityCard",
    role: "reserved",
    integrated: false,
    note: "ProbabilityCard renders a real Meter/SplitBar trust score — reserved rather than layered behind live data.",
  },
  predictionTimelineLoop: {
    id: "prediction-timeline-loop",
    path: "/assets/14-prediction-timeline-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "predictionStudio.resultTimeline",
    role: "background",
    integrated: true,
  },
  tacticalMapHeroBackground: {
    id: "tactical-map-hero-background",
    path: "/assets/15-tactical-map-hero-background.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "predictionStudio.header",
    role: "reserved",
    integrated: false,
    note: "Reserved to keep the form-dense Prediction Studio page free of extra background/contrast risk this pass — scenario building is the priority there, not ambiance.",
  },
  tacticalMapLoop: {
    id: "tactical-map-loop",
    path: "/assets/16-tactical-map-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "predictionStudio.header",
    role: "reserved",
    integrated: false,
    note: "Video alternate to tactical-map-hero-background — reserved for the same reason.",
  },
  dataStreamBackground: {
    id: "data-stream-background",
    path: "/assets/17-data-stream-background.png",
    type: "image",
    width: 2752,
    height: 1536,
    section: "landing.supportedTournaments",
    role: "background",
    integrated: true,
  },
  ambientLoop: {
    id: "ambient-loop",
    path: "/assets/18-ambient-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "landing.hero",
    role: "reserved",
    integrated: false,
    note: "Alternate hero ambiance — the hero already combines a video background with two code-based effects (HolographicNoiseOverlay, FloatingGlassObjects); a third motion layer here would be overload.",
  },
  finalCta: {
    id: "final-cta",
    path: "/assets/19-final-cta.png",
    type: "image",
    width: 2752,
    height: 1536,
    section: "landing.finalCta",
    role: "background",
    integrated: true,
  },
  footerBackground: {
    id: "footer-background",
    path: "/assets/20-footer-background.png",
    type: "image",
    width: 1528,
    height: 648,
    section: "layout.footer",
    role: "background",
    integrated: true,
  },
  loadingTransitionLoop: {
    id: "loading-transition-loop",
    path: "/assets/21-loading-transition-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "predictionStudio.scenarioBuilder",
    role: "reserved",
    integrated: false,
    note: "Reserved for a future loading-state treatment on scenario submission — introducing a new loading visual state is beyond this visual-integration pass's scope.",
  },
  aiCommandCenter: {
    id: "ai-command-center",
    path: "/assets/22-ai-command-center.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "landing.technology",
    role: "reserved",
    integrated: false,
    note: "Reserved for the documented-but-not-yet-built Technology Section (docs/19-landing-experience.md) — building that section is out of scope for this pass.",
  },
  aiTacticalCore: {
    id: "ai-tactical-core",
    path: "/assets/23-ai-tactical-core.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "landing.technology",
    role: "reserved",
    integrated: false,
    note: "Reserved for the same not-yet-built Technology Section as ai-command-center.",
  },
  premiumGlassMaterialLibrary: {
    id: "premium-glass-material-library",
    path: "/assets/24-premium-glass-material-library.png",
    type: "image",
    width: 2816,
    height: 1536,
    section: "landing.hero",
    role: "reserved",
    integrated: false,
    note: "Conceptual reference for the FloatingGlassObjects effect's material/palette — the effect is implemented in code (per instructions, effects 26-30 must not use generated video/imagery), so this still frame stays reserved rather than rendered directly.",
  },
  cinematicTransitionLoop: {
    id: "cinematic-transition-loop",
    path: "/assets/25-cinematic-transition-loop.mp4",
    type: "video",
    width: 2816,
    height: 1536,
    section: "predictionStudio.resultHeader",
    role: "background",
    integrated: true,
  },
} as const satisfies Record<string, MediaAsset>;

export type MediaAssetKey = keyof typeof MEDIA_ASSETS;
