import { buildTeamFeatureBlock, type FeatureRow, type TeamFeatureBlock } from "../../feature/types";

/** Shared FeatureRow fixture builder for modeling unit/integration tests — avoids repeating all 176 columns in every test. */

const DEFAULT_TEAM_BLOCK: TeamFeatureBlock = {
  PriorMatchCount: 0,
  PriorWins: 0,
  PriorLosses: 0,
  CumulativeWinRate: 0.5,
  PriorMapsPlayed: 0,
  PriorMapWins: 0,
  PriorMapLosses: 0,
  CumulativeMapWinRate: 0.5,
  IsColdStart: true,
  Last3MatchCount: 0,
  Last3WinRate: 0.5,
  Last5MatchCount: 0,
  Last5WinRate: 0.5,
  Last10MatchCount: 0,
  Last10WinRate: 0.5,
  Last30DayMatchCount: 0,
  Last30DayWinRate: 0.5,
  Last60DayMatchCount: 0,
  Last60DayWinRate: 0.5,
  RecentMapWinRateLast10: 0.5,
  RecentAvgMapsWonLast10: 0,
  RecentAvgMapsLostLast10: 0,
  FormTrend: 0,
  EloRating: 1500,
  EloWinProbability: 0.5,
  AvgOpponentEloLast5: 1500,
  AvgOpponentEloLast10: 1500,
  AvgOpponentWinRateLast5: 0.5,
  AvgOpponentWinRateLast10: 0.5,
  StrengthOfScheduleAllTime: 1500,
  WinsVsAboveMedianOpponentCount: 0,
  LossesVsBelowMedianOpponentCount: 0,
  MapPoolBreadth: 0,
  TopMapConcentration: 0,
  MapExperienceEntropy: 0,
  UnknownMapCount: 0,
  AvgRoundsWonPerMap: 0,
  AvgRoundsLostPerMap: 0,
  HasAttackDefenseSplitData: false,
  AttackSideWinRate: 0.5,
  DefenseSideWinRate: 0.5,
  DaysSinceLastMatch: null,
  HasPriorMatch: false,
  HoursSinceLastMatch: null,
  MatchesLast7Days: 0,
  MatchesLast14Days: 0,
  MatchesLast30Days: 0,
  MapsLast7Days: 0,
  MapsLast14Days: 0,
  MapsLast30Days: 0,
  IsBackToBack: false,
  SameDayMatchCountBeforeGroup: 0,
  InactivityFlag: false,
  RosterSnapshotAvailable: true,
  RosterSize: 5,
  PlayersWithPriorTeamAppearanceCount: 0,
  RosterContinuityVsPreviousMatch: 0,
  RosterContinuityLast3Matches: 0,
  SharedPriorMatchesAmongRosterAvg: 0,
  RosterAvgPlayerPriorAppearances: 0,
  RosterMinPlayerPriorAppearances: 0,
  RosterMaxPlayerPriorAppearances: 0,
  RosterDebutingPlayerCount: 5,
  DaysSinceRosterLastAppearedTogether: null,
  RosterAvgPlayerPriorWins: 0,
  RosterAvgPlayerRecentAppearances30Days: 0,
  RosterPriorInternationalAppearances: 0,
  RosterPriorMastersChampionsAppearances: 0,
};

let mockRowCounter = 0;

export function buildMockFeatureRow(overrides: Partial<FeatureRow> = {}): FeatureRow {
  mockRowCounter += 1;
  const base: FeatureRow = {
    matchInternalId: `vlr:match:mock-${mockRowCounter}`,
    providerMatchId: `mock-${mockRowCounter}`,
    scheduledAt: "2025-01-01T00:00:00.000Z",
    eventInternalId: "vlr:event:mock",
    eventFamily: "vct-americas",
    eventName: "Mock Event",
    eventRegion: "americas",
    eventStage: "regular-season",
    tournamentLevel: "league",
    matchStageDisplay: "Regular Season",
    seriesFormat: "bo3",
    teamAProviderId: "vlr:team:A",
    teamBProviderId: "vlr:team:B",
    teamADisplayName: "Mock Team A",
    teamBDisplayName: "Mock Team B",
    sourceDatasetVersion: "mock-source-version",
    featureSchemaVersion: "vlr-feature-schema@1.0.0",
    featureRulesVersion: "vlr-feature-rules@1.0.0",
    ...buildTeamFeatureBlock("teamA", DEFAULT_TEAM_BLOCK),
    ...buildTeamFeatureBlock("teamB", DEFAULT_TEAM_BLOCK),
    eloRatingDiff: 0,
    eloRatingVersion: "vlr-elo@1.0.0",
    knownMapPoolOverlapCount: 0,
    mapStrengthDifferential: 0,
    h2hPriorMeetingCount: 0,
    h2hTeamAWins: 0,
    h2hTeamBWins: 0,
    h2hTeamAWinRate: 0.5,
    h2hPriorMapDifferential: 0,
    h2hMeetingsLast90Days: 0,
    h2hMeetingsLast180Days: 0,
    h2hMeetingsLast365Days: 0,
    h2hMostRecentMeetingWinnerProviderId: "unknown",
    h2hMeetingsSameEventFamily: 0,
    h2hMeetingsSameEventRegion: 0,
    restDifferenceDays: null,
    eventStageMatchesLast3Days: 0,
    seasonYear: 2025,
    matchMonth: 1,
    isInternationalEvent: false,
    isRegionalLeague: true,
    isMastersOrChampions: false,
    labelTeamAWin: 1,
    labelWinnerProviderId: "vlr:team:A",
    labelSeriesScore: "2-0",
    labelMapCountPlayed: 2,
  };
  return { ...base, ...overrides };
}

export function resetMockFeatureRowCounter(): void {
  mockRowCounter = 0;
}
